In [1]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [2]:
# Cargue el dataset `data.csv`
data = pd.read_csv("data.csv")

# Cree un objeto de tipo `PolynomialFeatures` con grado `2`
poly = PolynomialFeatures(degree=2, include_bias=True)

# Transforme la columna `x` del dataset `data` usando el objeto `poly`
x_poly = poly.fit_transform(data[["x"]])


In [6]:
x_poly.shape

(20, 3)

In [21]:
# Fije la tasa de aprendizaje en 0.0001 y el número de iteraciones en 1000
learning_rate = 0.0001
n_iterations = 1000

# Defina el parámetro inicial `params` como un arreglo de tamaño 3 con ceros
params = np.zeros(x_poly.shape[1])
# inter =np.mean(np.array(data.y))
for epoch in range(n_iterations):

    # Compute el pronóstico con los parámetros actuales
    y_pred = np.dot(x_poly, params)

    # Calcule el error
    error = data.y - y_pred

    # Calcule el gradiente
    # b0 = -2*sum(error)
    b1 = -2*np.sum(np.multiply(x_poly, np.array(error)[:,np.newaxis]), axis=0)
    # b1 = -2*np.dot(x_poly.T, error) / len(data.y)

    # Actualice los parámetros
    # inter = inter +learning_rate*b0
    params = params - learning_rate * b1
    print(params)

[ 0.05115788 -0.07073648  0.52227198]
[ 0.08979664 -0.13980509  0.9131122 ]
[ 0.11906534 -0.20724514  1.20558761]
[ 0.14132077 -0.27309505  1.42444584]
[ 0.1583268  -0.33739231  1.58820828]
[ 0.17140349 -0.40017352  1.71073651]
[ 0.18153882 -0.46147443  1.80240471]
[ 0.1894722  -0.52132995  1.87097699]
[ 0.19575699 -0.57977415  1.9222641 ]
[ 0.20080737 -0.63684031  1.96061488]
[ 0.20493328 -0.69256093  1.98928404]
[ 0.2083667  -0.74696772  2.01070742]
[ 0.21128126 -0.80009168  2.02670805]
[ 0.21380688 -0.85196304  2.03865029]
[ 0.21604082 -0.90261134  2.04755525]
[ 0.21805586 -0.95206543  2.05418714]
[ 0.21990647 -1.00035345  2.05911789]
[ 0.22163341 -1.0475029   2.06277555]
[ 0.2232672  -1.09354063  2.06548048]
[ 0.22483068 -1.13849285  2.06747243]
[ 0.22634093 -1.18238515  2.06893083]
[ 0.22781076 -1.22524253  2.06998997]
[ 0.22924974 -1.26708939  2.07075037]
[ 0.23066503 -1.30794956  2.07128724]
[ 0.232062   -1.3478463   2.07165687]
[ 0.23344466 -1.38680232  2.0719014 ]
[ 0.23481603

In [14]:
params

array([ 0.86145071, -3.00001679,  2.01321365])

In [16]:
data.x

0    -4.0000
1    -3.5789
2    -3.1579
3    -2.7368
4    -2.3158
5    -1.8947
6    -1.4737
7    -1.0526
8    -0.6316
9    -0.2105
10    0.2105
11    0.6316
12    1.0526
13    1.4737
14    1.8947
15    2.3158
16    2.7368
17    3.1579
18    3.5789
19    4.0000
Name: x, dtype: float64

In [11]:
np.array(error).shape

(20,)